### PR TITLE
site changes

### PR DESCRIPTION
**Pull request by Ecorous**
Sorry for unverified commit, am currently on temp pc. I wasn't sure what to do about github icon in navbar for dark mode, so I hacked something together

### CODE REVIEW

**Comment by moehreag** [comment]
I personally don't really care about the unverified status but
- Are you sure the navbar height is fine like this? I seems a little thick.
- the icons on the buttons aren't centered vertically :/
- this may be caused by opening the page locally, but are you sure the discord icon loads correctly?

**Comment by Ecorous** [comment]
> I personally don't really care about the unverified status but
> 
>     * Are you sure the navbar height is fine like this? I seems a little thick.
> 
>     * the icons on the buttons aren't centered vertically :/
> 
>     * this may be caused by opening the page locally, but are you sure the discord icon loads correctly?

Mine loads locally

**Comment by Ecorous** [comment]
Not sure how to centre the icons vertically, and I think the navbar height is okay

**Comment by Ecorous** [comment]
image

**Comment by moehreag** [comment]
> > I personally don't really care about the unverified status but
> > ```
> > * Are you sure the navbar height is fine like this? I seems a little thick.
> > 
> > * the icons on the buttons aren't centered vertically :/
> > 
> > * this may be caused by opening the page locally, but are you sure the discord icon loads correctly?
> > ```
> 
> Mine loads locally

are you sure you pushed the icon file?

**Comment by Ecorous** [comment]
> > > I personally don't really care about the unverified status but
> > > ```
> > > * Are you sure the navbar height is fine like this? I seems a little thick.
> > > 
> > > * the icons on the buttons aren't centered vertically :/
> > > 
> > > * this may be caused by opening the page locally, but are you sure the discord icon loads correctly?
> > > ```
> > 
> > 
> > Mine loads locally
> 
> are you sure you pushed the icon file?

ggit momen

**Comment by moehreag** [comment]
the navbar still feels to thick in my opinion, and tbh if the icons on the buttons can't be centered vertically they shouldn't be there imo.

**Comment by Ecorous** [comment]
> the navbar still feels to thick in my opinion, and tbh if the icons on the buttons can't be centered vertically they shouldn't be there imo.

I can try and fix that in a couple of days

**Comment by moehreag** [comment]
> > the navbar still feels to thick in my opinion, and tbh if the icons on the buttons can't be centered vertically they shouldn't be there imo.
> 
> I can try and fix that in a couple of days

okay!

**Pull request closed without merging**
